FROM golang:1.12.0-alpine AS builder

COPY . /go/src/github.com/tommy-sho/microservice-sample/

WORKDIR /go/src/github.com/tommy-sho/microservice-sample/pkg/api

ENV GO111MODULE=on

RUN apk add alpine-sdk \
        git

RUN GOOS=linux GOARCH=amd64 go build -o api .

From alpine:latest
COPY --from=builder /go/src/github.com/tommy-sho/microservice-sample/pkg/api .

CMD ["./api"]
